// <auto-generated />
namespace GestaoSuperHeroi.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ConfigInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConfigInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "202311240117586_Config-Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
